# Generated by Django 6.0.4 on 2026-04-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('produto_telemetria', models.BooleanField(default=False)),
                ('produto_manutencao', models.BooleanField(default=False)),
                ('produto_financeiro', models.BooleanField(default=False)),
                ('produto_ia_assistente', models.BooleanField(default=False)),
                ('produto_roteirizacao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
